includes:
  - https://github.ibm.com/cloud-docs/container-registry-cli-plugin
  - https://github.ibm.com/cloud-docs/containers
  - https://github.ibm.com/cloud-docs/RegistryImages
  - https://github.ibm.com/cloud-docs-solutions/solution-tutorials
  - https://github.ibm.com/cloud-docs/va
